### ISSUE TITLE
@ character preventing stream tracking

### ISSUE THREAD

**Issue by marcinrosinski** [datasift/datasift-php#30]
Hi guys,

There seems to be an issue where if @reply is being used as a value for interaction.content contains "" its not beeing tracked. Should we somehow encode/escape it as plain one is not being picked up for you.

**Comment by paulmozo** [comment]
Mentions are stripped from [interaction.content](http://dev.datasift.com/docs/targets/common-interaction/interaction-content), if you want to filter on mentions you can either use interaction.mentions or interaction.raw_content
